// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFrAuxQVyoQ1WgX8q8AGwfFQs4Vj10WIo',
    appId: '1:854330068599:web:d689813c36a3b142ad4072',
    messagingSenderId: '854330068599',
    projectId: 'authtut-3f3fb',
    authDomain: 'authtut-3f3fb.firebaseapp.com',
    storageBucket: 'authtut-3f3fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyq2diC47HAK53DUU21m4vlUxtCcLLAc',
    appId: '1:854330068599:android:62cc0f5679f9b5c5ad4072',
    messagingSenderId: '854330068599',
    projectId: 'authtut-3f3fb',
    storageBucket: 'authtut-3f3fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxxzpP0WKENArITtCQ-oktF_g7bJpD1k',
    appId: '1:854330068599:ios:1b1651ecea1ed28dad4072',
    messagingSenderId: '854330068599',
    projectId: 'authtut-3f3fb',
    storageBucket: 'authtut-3f3fb.appspot.com',
    iosBundleId: 'com.example.loginauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxxzpP0WKENArITtCQ-oktF_g7bJpD1k',
    appId: '1:854330068599:ios:75721767b2ecc4a5ad4072',
    messagingSenderId: '854330068599',
    projectId: 'authtut-3f3fb',
    storageBucket: 'authtut-3f3fb.appspot.com',
    iosBundleId: 'com.example.loginauth.RunnerTests',
  );
}
